### ISSUE TITLE
Funcionalidad para Hacer Checkin, Enviar Updates y Hacer Checkout

### ISSUE THREAD

**Issue by lingow** [lingow/BusWatch#3]
Hay que diseñar un algoritmo para agregar nuevos puntos a una ruta

**Comment by miguelsalazar** [comment]
Check-in:
Recibir un identificador de ruta (Route ID) y regresar un hash.

**Comment by lingow** [comment]
Ahora las rutas están expresadas como una lista de caminos ( una lista de listas de latlng ) De manera que cada vez que se hace un checkout, se agrega el camino recorrido a la lista de caminos, ahora llamada routePaths. 

Este cambio fue para resolver el problema de una ruta que esté compuesta por varios caminos que varios usuarios han dado, aunque estén desconectados.

**Comment by lingow** [comment]
También me faltó mencionar que cada ruta tiene un atributo llamado unitPoints. Estos son los puntos en los que hay alguien en medio de un checkin para esa ruta. Hay que actualizar ese campo como parte del método de UpdateCheckin

**Comment by lingow** [comment]
Ya que todo el server va a correr en memoria, podrías considerar que sería más facil usar una secuencia de enteros en lugar de generar hashes para cada checkin. A fin de cuentas, solamente interesa identificar a cada checkin en curso.
